# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

minecraft_version=1.21.2
yarn_mappings=1.21.2+build.1
loader_version=0.16.10

mod_version=1.21.2-1.1.2
maven_group=ru.feytox
archives_base_name=showyourself

fabric_version=0.106.1+1.21.2

midnightlib_version = 1.6.4-fabric
modmenu_version = 12.0.0
